In [1]:
import os, gc, sys
from glob import glob
from tqdm.notebook import tqdm

import pandas as pd

In [2]:
prefix = os.getcwd().split("jdi-qasp-ml")[0]
sys.path.append(os.path.join(prefix, "jdi-qasp-ml"))
model_path = os.path.join(prefix, "jdi-qasp-ml", "MUI_model/model")
df_path = os.path.join(prefix, "jdi-qasp-ml", "data/mui_dataset/df")

In [3]:
# ds_files = glob(f"{df_path}/site*.pkl")
# df = pd.DataFrame()
# for file in tqdm(ds_files[:200]):
#     df = pd.concat([df, pd.read_pickle(file)]).reset_index(drop=True)

# df.to_parquet(f"{prefix}jdi-qasp-ml/data/mui_dataset/mui_full_dataset.parquet")

In [4]:
df = pd.read_parquet(f"{prefix}jdi-qasp-ml/data/mui_dataset/mui_full_dataset.parquet")

FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mikhail_Bulgakov/GitRepo/jdi-qasp-ml/data/mui_dataset/mui_full_dataset.parquet'

In [5]:
df['attributes_list'] = df.attributes.apply(lambda x: [] if x is None else list(x.keys()))

NameError: name 'df' is not defined

Let's see what attributes are used in train dataset

In [7]:
import itertools
lists = df.attributes_list[df.attributes_list.apply(lambda x: True if "data-label" in x else False)].to_list()
print(set(list(itertools.chain.from_iterable(lists))))

{'aria-invalid', 'aria-haspopup', 'aria-multiselectable', 'x', 'role', 'aria-hidden', 'viewBox', 'aria-labelledby', 'class', 'cy', 'charset', 'data-mode', 'aria-controls', 'menuprops', 'data-label', 'r', 'aria-label', 'typenumber', 'data-id', 'data-field', 'aria-colcount', 'title', 'data-colindex', 'aria-checked', 'aria-valuenow', 'src', 'aria-selected', 'href', 'y', 'data-shrink', 'placeholder', 'focusable', 'stroke-width', 'style', 'required', 'rows', 'cx', 'aria-sort', 'disabled', 'data-index', 'autocomplete', 'novalidate', 'draggable', 'text-anchor', 'data-test', 'tabindex', 'content', 'rel', 'name', 'aria-valuemax', 'colspan', 'multiple', 'aria-expanded', 'fill', 'data-rowselected', 'readonly', 'aria-current', 'lang', 'aria-rowcount', 'data-rowindex', 'for', 'aria-describedby', 'id', 'data-indeterminate', 'checked', 'data-meta', 'aria-orientation', 'value', 'd', 'aria-colindex', 'direction', 'scope', 'aria-disabled', 'type', 'data-jss', 'aria-valuemin', 'data-value', 'aria-rowinde

In [8]:
final_atrributes = set(list(itertools.chain.from_iterable(lists))) - set(['type', 'href', 'role', 'class', 'data-label'])
final_atrributes

{'aria-checked',
 'aria-colcount',
 'aria-colindex',
 'aria-controls',
 'aria-current',
 'aria-describedby',
 'aria-disabled',
 'aria-expanded',
 'aria-haspopup',
 'aria-hidden',
 'aria-invalid',
 'aria-label',
 'aria-labelledby',
 'aria-multiselectable',
 'aria-orientation',
 'aria-rowcount',
 'aria-rowindex',
 'aria-selected',
 'aria-sort',
 'aria-valuemax',
 'aria-valuemin',
 'aria-valuenow',
 'autocomplete',
 'charset',
 'checked',
 'colspan',
 'content',
 'cx',
 'cy',
 'd',
 'data-colindex',
 'data-field',
 'data-id',
 'data-indeterminate',
 'data-index',
 'data-jss',
 'data-meta',
 'data-mode',
 'data-rowindex',
 'data-rowselected',
 'data-shrink',
 'data-test',
 'data-value',
 'direction',
 'disabled',
 'draggable',
 'fill',
 'focusable',
 'for',
 'id',
 'lang',
 'menuprops',
 'multiple',
 'name',
 'novalidate',
 'placeholder',
 'r',
 'readonly',
 'rel',
 'required',
 'rows',
 'scope',
 'src',
 'stroke-width',
 'style',
 'tabindex',
 'text-anchor',
 'title',
 'typenumber',
 'val

Investigate Class 

In [9]:
df_labeled = df[df.attributes_list.apply(lambda x: True if "data-label" in x else False)].copy()

In [10]:
df_labeled['classes'] = df_labeled.attributes.apply(lambda x: None if x is None else x.get('class'))

In [11]:
len(df_labeled.classes)

286573

In [79]:
attr_class_series = df_labeled.classes[~df_labeled.classes.isna()].apply(lambda x: x.replace("-", " "))
class_vocab = list(
            itertools.chain.from_iterable(
                attr_class_series.apply(lambda x: x.split(sep=" "))
            )
        )

In [80]:
class_vocab

['MuiFormControl',
 'root',
 'MuiFormLabel',
 'root',
 'MuiFormGroup',
 'root',
 'MuiFormGroup',
 'row',
 'MuiFormControlLabel',
 'root',
 'MuiFormControlLabel',
 'labelPlacementBottom',
 'MuiButtonBase',
 'root',
 'MuiIconButton',
 'root',
 'jss1',
 'MuiRadio',
 'root',
 'MuiRadio',
 'colorSecondary',
 'MuiIconButton',
 'colorSecondary',
 'MuiIconButton',
 'label',
 'jss4',
 'jss5',
 'MuiSvgIcon',
 'root',
 'MuiSvgIcon',
 'root',
 'jss6',
 'MuiTouchRipple',
 'root',
 'MuiTypography',
 'root',
 'MuiFormControlLabel',
 'label',
 'MuiTypography',
 'body1',
 'MuiFormControlLabel',
 'root',
 'MuiFormControlLabel',
 'labelPlacementBottom',
 'MuiButtonBase',
 'root',
 'MuiIconButton',
 'root',
 'jss1',
 'MuiRadio',
 'root',
 'MuiRadio',
 'colorSecondary',
 'MuiIconButton',
 'colorSecondary',
 'MuiIconButton',
 'label',
 'jss4',
 'jss5',
 'MuiSvgIcon',
 'root',
 'MuiSvgIcon',
 'root',
 'jss6',
 'MuiTouchRipple',
 'root',
 'MuiTypography',
 'root',
 'MuiFormControlLabel',
 'label',
 'MuiTypogr

In [83]:
pd.Series(class_vocab).value_counts().sort_values(ascending=False).head(10)

root              196325
MuiTypography      79063
MuiIconButton      41680
label              29907
MuiChip            27557
MuiButtonBase      27399
MuiSvgIcon         25343
MuiTouchRipple     23792
MuiTableCell       21468
Mui                15935
dtype: int64

In [47]:
s = 'MuiFormControlLabel root'
s = 'r'
s = s[0].upper()+s[1:]
" ".join(list(itertools.chain.from_iterable([i.lower().split(" ")  for i in re.findall(r'[A-Z][^A-Z]*', s)])))

'r'

We need to exclude "root" from classes vocabulary

In [84]:
class_vocab

['MuiFormControl',
 'root',
 'MuiFormLabel',
 'root',
 'MuiFormGroup',
 'root',
 'MuiFormGroup',
 'row',
 'MuiFormControlLabel',
 'root',
 'MuiFormControlLabel',
 'labelPlacementBottom',
 'MuiButtonBase',
 'root',
 'MuiIconButton',
 'root',
 'jss1',
 'MuiRadio',
 'root',
 'MuiRadio',
 'colorSecondary',
 'MuiIconButton',
 'colorSecondary',
 'MuiIconButton',
 'label',
 'jss4',
 'jss5',
 'MuiSvgIcon',
 'root',
 'MuiSvgIcon',
 'root',
 'jss6',
 'MuiTouchRipple',
 'root',
 'MuiTypography',
 'root',
 'MuiFormControlLabel',
 'label',
 'MuiTypography',
 'body1',
 'MuiFormControlLabel',
 'root',
 'MuiFormControlLabel',
 'labelPlacementBottom',
 'MuiButtonBase',
 'root',
 'MuiIconButton',
 'root',
 'jss1',
 'MuiRadio',
 'root',
 'MuiRadio',
 'colorSecondary',
 'MuiIconButton',
 'colorSecondary',
 'MuiIconButton',
 'label',
 'jss4',
 'jss5',
 'MuiSvgIcon',
 'root',
 'MuiSvgIcon',
 'root',
 'jss6',
 'MuiTouchRipple',
 'root',
 'MuiTypography',
 'root',
 'MuiFormControlLabel',
 'label',
 'MuiTypogr

In [149]:
classes = list(itertools.chain.from_iterable(pd.read_csv("/Users/Mikhail_Bulgakov/GitRepo/jdi-qasp-ml/data/mui_dataset/classes.txt").values.tolist()))
print(classes)

['backdrop', 'icon', 'link', 'avatar', 'paper', 'bottom-navigation', 'menu', 'stepper', 'progress', 'box', 'dialog', 'button', 'card', 'switch', 'typography', 'container', 'table', 'popper', 'breadcrumbs', 'list', 'alert', 'chip', 'select', 'textarea-autosize', 'accordion', 'text-field', 'radio', 'checkbox', 'drawer', 'grid', 'popover', 'snackbar', 'radiogroup', 'slider', 'divider', 'badge', 'app-bar', 'button-group', 'tabs']


In [150]:
len(classes)

39

In [125]:
new = pd.Series(class_vocab, index = class_vocab).apply(lambda cl: np.array([1 if i in cl.lower() else 0 for i in classes]))

In [144]:
arr = np.zeros((new.shape[0], len(classes)))
for i,r in enumerate(new):
    arr[i,:] = r
arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [153]:
d1 = arr[:50]
d2 = arr[50:100]
np.hstack((d1,d2)).shape
    

(50, 78)

In [126]:
pd.DataFrame(new)

0
MuiFormControl  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
root            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
MuiFormLabel    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
root            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
MuiFormGroup    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
...                                                           ...
MuiTypography   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...
root            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
jss75           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
MuiTypography   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...
body1           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[979333 rows x 1 columns]

In [121]:
import numpy as np
n1 = new[:40]
n2 = new[40:50]
np.concatenate((n1,n2))

array([array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       array([0, 0, 

ROLES

In [111]:
attr_role_series = (
            df_labeled
            .attributes.apply(lambda x: None if type(x) is not dict else x.get("role"))
        )

In [113]:
attr_role_series[~attr_role_series.isna()].value_counts()

presentation         8371
button               6512
cell                 2070
tab                  1218
region                912
menuitem              861
separator             626
progressbar           578
alert                 541
menu                  383
slider                370
radiogroup            321
group                 295
tooltip               287
tablist               264
dialog                264
none presentation     264
row                   240
checkbox              240
columnheader          200
listitem              117
grid                   40
list                   39
Name: attributes, dtype: int64

In [6]:
df_499 = pd.read_pickle("/Users/Mikhail_Bulgakov/GitRepo/jdi-qasp-ml/data/mui_dataset/df/site-499.pkl")
id_string = '<div class="MuiButtonBase-root MuiListItem-root MuiListItem-gutters MuiListItem-divider MuiListItem-button" tabindex="0" role="button" aria-disabled="false"><div class="MuiListItemText-root"><span class="MuiTypography-root MuiListItemText-primary MuiTypography-body1 MuiTypography-displayBlock">Drafts</span></div><span class="MuiTouchRipple-root"></span></div>'

In [8]:
df_499['attributes_list'] = df_499.attributes.apply(lambda x: [] if x is None else list(x.keys()))
# df_499[df_499.attributes_list.apply(lambda x: True if (("aria-disabled" in x) and ("tabindex" in x) and ("role" in x)) else False)].loc[1347]

In [14]:
df_499["label"] = df_499.attributes.apply(lambda x: None if x is None else x.get("data-label"))
df_499_labeled = df_499[~df_499.label.isna()].copy()

In [20]:
import itertools

In [31]:
pd.DataFrame({obj:df_499_labeled.groupby("label").style.agg(lambda x: list(set(itertools.chain.from_iterable(x))))[obj] 
                for obj in df_499_labeled.groupby("label").style.agg(lambda x: list(set(itertools.chain.from_iterable(x)))).index})[["button", "radio"]]

button                         radio
0                 scroll-behavior               scroll-behavior
1     -webkit-hyphenate-character   -webkit-hyphenate-character
2             animation-direction           animation-direction
3        border-block-start-width      border-block-start-width
4                         hyphens                       hyphens
..                            ...                           ...
327        border-block-end-width        border-block-end-width
328                 flood-opacity                 flood-opacity
329                 shape-outside                 shape-outside
330  -webkit-mask-box-image-slice  -webkit-mask-box-image-slice
331     border-inline-start-color     border-inline-start-color

[332 rows x 2 columns]

In [17]:
df_499_labeled

attributes  displayed  \
120   {'class': 'MuiDrawer-root MuiDrawer-docked jss...       True   
123   {'class': 'MuiDivider-root', 'data-label': 'di...      False   
124   {'class': 'MuiList-root MuiList-padding', 'dat...       True   
125   {'aria-disabled': 'false', 'class': 'MuiButton...       True   
127   {'aria-hidden': 'true', 'class': 'MuiSvgIcon-r...       True   
...                                                 ...        ...   
1116  {'class': 'MuiPaper-root MuiPaper-elevation1 M...       True   
1117  {'class': 'MuiTypography-root jss56 MuiTypogra...       True   
1118  {'class': 'MuiPopover-root', 'data-label': 'po...       True   
1122  {'class': 'MuiTypography-root jss85 MuiTypogra...       True   
1125  {'data-label': 'popper', 'role': 'tooltip', 's...       True   

                        element_id       height onmouseenter onmouseover  \
120   6932874036556138214282815018   434.000000         None        None   
123   1020730951556138214617022005     1.000000         None        None   
124   1485373126556138215821397030   208.000000         None        None   
125   7619432732556138211657671930    48.000000         None        None   
127   5006822130556138215329088562    24.000000         None        None   
...                            ...          ...          ...         ...   
1116  2997734401556138224550088524    56.000000         None        None   
1117  7996883338556138223728211052    56.000000         None        None   
1118  9532308721556138227446723085  6654.000000         None        None   
1122  1027648080556138223518938445    56.000000         None        None   
1125  2458135316556138223806734564    38.015625         None        None   

                         parent_id  \
120   5582676598556138214888320459   
123   3203935096556138219356400743   
124   3203935096556138219356400743   
125   1485373126556138215821397030   
127   1550596268556138214644857026   
...                            ...   
1116  4490717197556138228694315242   
1117  2997734401556138224550088524   
1118  9301401088556138216135889332   
1122  4303492041556138227684109879   
1125  9301401088556138216135889332   

                                                  style tag_name  \
120   [accent-color, align-content, align-items, ali...      DIV   
123   [accent-color, align-content, align-items, ali...       HR   
124   [accent-color, align-content, align-items, ali...       UL   
125   [accent-color, align-content, align-items, ali...      DIV   
127   [accent-color, align-content, align-items, ali...      svg   
...                                                 ...      ...   
1116  [accent-color, align-content, align-items, ali...      DIV   
1117  [accent-color, align-content, align-items, ali...        P   
1118  [accent-color, align-content, align-items, ali...      DIV   
1122  [accent-color, align-content, align-items, ali...        P   
1125  [accent-color, align-content, align-items, ali...      DIV   

                                                   text        width      x  \
120   Inbox\nStarred\nSend email\nDrafts\nAll mail\n...   240.000000    0.0   
123                                                       239.000000    1.0   
124                  Inbox\nStarred\nSend email\nDrafts   239.000000    1.0   
125                                               Inbox   239.000000    1.0   
127                                                None    24.000000   17.0   
...                                                 ...          ...    ...   
1116                         The content of the Popper.   224.500000    0.0   
1117                         The content of the Popper.   224.500000    0.0   
1118                        The content of the Popover.  1227.000000    0.0   
1122                        The content of the Popover.   232.640625  497.0   
1125                         The content of the Popper.   186.921875    0.0   

           y                                    attributes_list     